#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Read all lines from 六级-乱序.txt, generate derivatives & phrases,
split into 50+ batch JSON files.
"""
import os, re, json, sys

SRC = r'f:\66666\docs\4 六级-乱序.txt'
OUT = r'f:\66666\docs\data'

# --- derivatives map (base -> {derivative: pos}) ---
DERIV = {
    'abandon':{'abandonment':'n.','abandoned':'adj.'},
    'absorb':{'absorption':'n.','absorbed':'adj.'},
    'abstract':{'abstraction':'n.','abstractly':'adv.'},
    'abundant':{'abundance':'n.','abundantly':'adv.'},
    'accelerate':{'acceleration':'n.','accelerating':'adj.'},
    'accept':{'acceptance':'n.','acceptable':'adj.'},
    'access':{'accessible':'adj.','accessibility':'n.'},
    'accommodate':{'accommodation':'n.'},
    'accompany':{'accompaniment':'n.'},
    'accomplish':{'accomplishment':'n.','accomplished':'adj.'},
    'accurate':{'accuracy':'n.','accurately':'adv.'},
    'achieve':{'achievement':'n.','achievable':'adj.'},
    'acknowledge':{'acknowledgement':'n.'},
    'acquire':{'acquisition':'n.','acquired':'adj.'},
    'adapt':{'adaptation':'n.','adaptable':'adj.'},
    'addict':{'addiction':'n.','addictive':'adj.'},
    'adjust':{'adjustment':'n.','adjustable':'adj.'},
    'admire':{'admiration':'n.','admirable':'adj.'},
    'adopt':{'adoption':'n.','adoptive':'adj.'},
    'advance':{'advancement':'n.','advanced':'adj.'},
    'advertise':{'advertisement':'n.'},
    'affect':{'affection':'n.','affected':'adj.'},
    'agree':{'agreement':'n.','agreeable':'adj.'},
    'allocate':{'allocation':'n.'},
    'alter':{'alteration':'n.','alternative':'adj.'},
    'amaze':{'amazement':'n.','amazing':'adj.'},
    'analyze':{'analysis':'n.','analytical':'adj.'},
    'announce':{'announcement':'n.'},
    'anticipate':{'anticipation':'n.'},
    'anxious':{'anxiety':'n.','anxiously':'adv.'},
    'apologize':{'apology':'n.'},
    'apply':{'application':'n.','applicable':'adj.'},
    'appoint':{'appointment':'n.','appointed':'adj.'},
    'appreciate':{'appreciation':'n.','appreciative':'adj.'},
    'approach':{'approachable':'adj.'},
    'approve':{'approval':'n.','approved':'adj.'},
    'argue':{'argument':'n.','argumentative':'adj.'},
    'arrange':{'arrangement':'n.'},
    'assess':{'assessment':'n.'},
    'assign':{'assignment':'n.','assigned':'adj.'},
    'assist':{'assistance':'n.','assistant':'n.'},
    'associate':{'association':'n.','associated':'adj.'},
    'assume':{'assumption':'n.'},
    'assure':{'assurance':'n.','assured':'adj.'},
    'attach':{'attachment':'n.','attached':'adj.'},
    'attack':{'attacker':'n.'},
    'attend':{'attendance':'n.','attendant':'n.'},
    'attract':{'attraction':'n.','attractive':'adj.'},
    'authorize':{'authorization':'n.'},
    'avoid':{'avoidance':'n.','unavoidable':'adj.'},
    'aware':{'awareness':'n.'},
    'balance':{'balanced':'adj.'},
    'bear':{'bearable':'adj.','unbearable':'adj.'},
    'believe':{'belief':'n.','believable':'adj.'},
    'benefit':{'beneficial':'adj.','beneficiary':'n.'},
    'bore':{'boredom':'n.','boring':'adj.'},
    'bound':{'boundary':'n.'},
    'brief':{'briefly':'adv.','brevity':'n.'},
    'calculate':{'calculation':'n.','calculator':'n.'},
    'capable':{'capability':'n.','incapable':'adj.'},
    'capture':{'captive':'n.','captivity':'n.'},
    'caution':{'cautious':'adj.','cautiously':'adv.'},
    'celebrate':{'celebration':'n.','celebrated':'adj.'},
    'certify':{'certification':'n.','certified':'adj.'},
    'challenge':{'challenging':'adj.'},
    'characterize':{'characteristic':'adj.','character':'n.'},
    'classify':{'classification':'n.','classified':'adj.'},
    'collapse':{'collapsed':'adj.'},
    'collect':{'collection':'n.','collective':'adj.'},
    'combine':{'combination':'n.','combined':'adj.'},
    'commit':{'commitment':'n.','committed':'adj.'},
    'communicate':{'communication':'n.'},
    'compare':{'comparison':'n.','comparable':'adj.'},
    'compensate':{'compensation':'n.'},
    'compete':{'competition':'n.','competitive':'adj.'},
    'complain':{'complaint':'n.'},
    'complete':{'completion':'n.','completely':'adv.'},
    'complex':{'complexity':'n.'},
    'compose':{'composition':'n.','composer':'n.'},
    'concentrate':{'concentration':'n.','concentrated':'adj.'},
    'concern':{'concerning':'prep.','concerned':'adj.'},
    'conclude':{'conclusion':'n.','conclusive':'adj.'},
    'conduct':{'conductor':'n.','conduction':'n.'},
    'confirm':{'confirmation':'n.','confirmed':'adj.'},
    'confuse':{'confusion':'n.','confused':'adj.'},
    'connect':{'connection':'n.','connected':'adj.'},
    'conscious':{'consciousness':'n.','unconscious':'adj.'},
    'conserve':{'conservation':'n.','conservative':'adj.'},
    'consider':{'consideration':'n.','considerable':'adj.'},
    'consist':{'consistent':'adj.','consistency':'n.'},
    'construct':{'construction':'n.','constructive':'adj.'},
    'consume':{'consumption':'n.','consumer':'n.'},
    'contain':{'container':'n.'},
    'contaminate':{'contamination':'n.'},
    'continue':{'continuous':'adj.','continuation':'n.'},
    'contribute':{'contribution':'n.','contributor':'n.'},
    'convert':{'conversion':'n.'},
    'convince':{'convincing':'adj.','convinced':'adj.'},
    'cooperate':{'cooperation':'n.','cooperative':'adj.'},
    'correspond':{'correspondence':'n.','corresponding':'adj.'},
    'corrupt':{'corruption':'n.','corrupted':'adj.'},
    'create':{'creation':'n.','creative':'adj.'},
    'criticize':{'criticism':'n.','critical':'adj.'},
    'cultivate':{'cultivation':'n.','cultivated':'adj.'},
    'curious':{'curiosity':'n.','curiously':'adv.'},
    'damage':{'damaging':'adj.','damaged':'adj.'},
    'deal':{'dealer':'n.'},
    'debate':{'debatable':'adj.'},
    'deceive':{'deception':'n.','deceptive':'adj.'},
    'decide':{'decision':'n.','decisive':'adj.'},
    'declare':{'declaration':'n.'},
    'decline':{'declining':'adj.'},
    'decorate':{'decoration':'n.','decorative':'adj.'},
    'defend':{'defense':'n.','defensive':'adj.'},
    'define':{'definition':'n.','definitive':'adj.'},
    'deliver':{'delivery':'n.','delivered':'adj.'},
    'demand':{'demanding':'adj.'},
    'demonstrate':{'demonstration':'n.'},
    'depend':{'dependence':'n.','dependent':'adj.'},
    'depress':{'depression':'n.','depressed':'adj.'},
    'deprive':{'deprivation':'n.','deprived':'adj.'},
    'describe':{'description':'n.','descriptive':'adj.'},
    'deserve':{'deserving':'adj.'},
    'design':{'designer':'n.','designed':'adj.'},
    'destroy':{'destruction':'n.','destructive':'adj.'},
    'detect':{'detection':'n.','detective':'n.'},
    'determine':{'determination':'n.','determined':'adj.'},
    'develop':{'development':'n.','developing':'adj.'},
    'devote':{'devotion':'n.','devoted':'adj.'},
    'differ':{'difference':'n.','different':'adj.'},
    'direct':{'direction':'n.','directly':'adv.'},
    'discover':{'discovery':'n.'},
    'discuss':{'discussion':'n.'},
    'dismiss':{'dismissal':'n.'},
    'dispose':{'disposal':'n.','disposable':'adj.'},
    'distinct':{'distinction':'n.','distinctive':'adj.'},
    'distinguish':{'distinguished':'adj.'},
    'distribute':{'distribution':'n.'},
    'divide':{'division':'n.','divided':'adj.'},
    'dominate':{'domination':'n.','dominant':'adj.'},
    'donate':{'donation':'n.'},
    'doubt':{'doubtful':'adj.','undoubtedly':'adv.'},
    'economy':{'economic':'adj.','economical':'adj.'},
    'edit':{'edition':'n.','editor':'n.'},
    'educate':{'education':'n.','educational':'adj.'},
    'effective':{'effectively':'adv.','effectiveness':'n.'},
    'efficient':{'efficiency':'n.','efficiently':'adv.'},
    'elect':{'election':'n.','electoral':'adj.'},
    'elevate':{'elevation':'n.','elevated':'adj.'},
    'eliminate':{'elimination':'n.'},
    'emerge':{'emergence':'n.','emerging':'adj.'},
    'emotion':{'emotional':'adj.','emotionally':'adv.'},
    'emphasize':{'emphasis':'n.','emphatic':'adj.'},
    'employ':{'employment':'n.','employer':'n.','employee':'n.'},
    'encourage':{'encouragement':'n.','encouraging':'adj.'},
    'engage':{'engagement':'n.','engaged':'adj.'},
    'enhance':{'enhancement':'n.','enhanced':'adj.'},
    'enjoy':{'enjoyment':'n.','enjoyable':'adj.'},
    'enrich':{'enrichment':'n.','enriched':'adj.'},
    'entertain':{'entertainment':'n.','entertaining':'adj.'},
    'enthusiasm':{'enthusiastic':'adj.'},
    'environment':{'environmental':'adj.'},
    'establish':{'establishment':'n.','established':'adj.'},
    'evaluate':{'evaluation':'n.'},
    'evidence':{'evident':'adj.','evidently':'adv.'},
    'evolve':{'evolution':'n.','evolving':'adj.'},
    'examine':{'examination':'n.'},
    'except':{'exception':'n.','exceptional':'adj.'},
    'excite':{'excitement':'n.','exciting':'adj.'},
    'exclude':{'exclusion':'n.','exclusive':'adj.'},
    'execute':{'execution':'n.','executive':'n.'},
    'exhaust':{'exhaustion':'n.','exhausted':'adj.'},
    'exhibit':{'exhibition':'n.'},
    'exist':{'existence':'n.','existing':'adj.'},
    'expand':{'expansion':'n.','expanding':'adj.'},
    'expect':{'expectation':'n.','expected':'adj.'},
    'explain':{'explanation':'n.'},
    'exploit':{'exploitation':'n.'},
    'explore':{'exploration':'n.','exploratory':'adj.'},
    'expose':{'exposure':'n.','exposed':'adj.'},
    'express':{'expression':'n.','expressive':'adj.'},
    'extend':{'extension':'n.','extensive':'adj.'},
    'extreme':{'extremely':'adv.','extremity':'n.'},
    'facilitate':{'facilitation':'n.'},
    'familiar':{'familiarity':'n.','familiarize':'v.'},
    'fascinate':{'fascination':'n.','fascinating':'adj.'},
    'finance':{'financial':'adj.','financially':'adv.'},
    'fit':{'fitting':'adj.','fitness':'n.'},
    'flexible':{'flexibility':'n.'},
    'focus':{'focused':'adj.'},
    'form':{'formation':'n.'},
    'formulate':{'formulation':'n.'},
    'fortunate':{'fortunately':'adv.','unfortunately':'adv.'},
    'foster':{'fostered':'adj.'},
    'found':{'foundation':'n.','founder':'n.'},
    'fragile':{'fragility':'n.'},
    'frequent':{'frequency':'n.','frequently':'adv.'},
    'fulfill':{'fulfillment':'n.','fulfilled':'adj.'},
    'function':{'functional':'adj.'},
    'generate':{'generation':'n.','generator':'n.'},
    'generous':{'generosity':'n.'},
    'govern':{'government':'n.','governing':'adj.'},
    'graduate':{'graduation':'n.','undergraduate':'n.'},
    'guide':{'guidance':'n.','guiding':'adj.'},
    'harm':{'harmful':'adj.','harmless':'adj.'},
    'harmony':{'harmonious':'adj.'},
    'health':{'healthy':'adj.'},
    'hesitate':{'hesitation':'n.','hesitant':'adj.'},
    'honor':{'honorary':'adj.','honored':'adj.'},
    'hush':{'hushed':'adj.'},
    'identify':{'identification':'n.','identity':'n.'},
    'ignore':{'ignorance':'n.','ignorant':'adj.'},
    'illuminate':{'illumination':'n.'},
    'illustrate':{'illustration':'n.','illustrative':'adj.'},
    'imagine':{'imagination':'n.','imaginative':'adj.'},
    'implement':{'implementation':'n.'},
    'imply':{'implication':'n.','implied':'adj.'},
    'impose':{'imposition':'n.'},
    'impress':{'impression':'n.','impressive':'adj.'},
    'improve':{'improvement':'n.','improved':'adj.'},
    'incorporate':{'incorporation':'n.'},
    'indicate':{'indication':'n.','indicative':'adj.'},
    'induce':{'induction':'n.','inducement':'n.'},
    'infect':{'infection':'n.','infectious':'adj.'},
    'influence':{'influential':'adj.'},
    'inform':{'information':'n.','informative':'adj.'},
    'inherit':{'inheritance':'n.','inherited':'adj.'},
    'innovate':{'innovation':'n.','innovative':'adj.'},
    'insist':{'insistence':'n.','insistent':'adj.'},
    'inspect':{'inspection':'n.','inspector':'n.'},
    'inspire':{'inspiration':'n.','inspiring':'adj.'},
    'install':{'installation':'n.'},
    'instruct':{'instruction':'n.'},
    'integrate':{'integration':'n.','integrated':'adj.'},
    'intelligent':{'intelligence':'n.'},
    'intend':{'intention':'n.','intended':'adj.'},
    'intense':{'intensity':'n.','intensely':'adv.'},
    'interact':{'interaction':'n.','interactive':'adj.'},
    'interpret':{'interpretation':'n.'},
    'intervene':{'intervention':'n.'},
    'invest':{'investment':'n.','investor':'n.'},
    'investigate':{'investigation':'n.'},
    'involve':{'involvement':'n.','involved':'adj.'},
    'irritate':{'irritation':'n.','irritating':'adj.'},
    'isolate':{'isolation':'n.','isolated':'adj.'},
    'judge':{'judgment':'n.','judicial':'adj.'},
    'justify':{'justification':'n.','justified':'adj.'},
    'lead':{'leader':'n.','leadership':'n.'},
    'legal':{'legally':'adv.'},
    'liberal':{'liberate':'v.','liberation':'n.'},
    'limit':{'limitation':'n.','limited':'adj.'},
    'locate':{'location':'n.','located':'adj.'},
    'logic':{'logical':'adj.','logically':'adv.'},
    'maintain':{'maintenance':'n.'},
    'major':{'majority':'n.'},
    'manage':{'management':'n.','manager':'n.'},
    'manipulate':{'manipulation':'n.','manipulative':'adj.'},
    'manufacture':{'manufacturing':'n.','manufacturer':'n.'},
    'measure':{'measurement':'n.','measurable':'adj.'},
    'memorize':{'memory':'n.','memorable':'adj.'},
    'migrate':{'migration':'n.','immigrant':'n.'},
    'modify':{'modification':'n.'},
    'monitor':{'monitoring':'n.'},
    'motivate':{'motivation':'n.','motivated':'adj.'},
    'mystery':{'mysterious':'adj.','mysteriously':'adv.'},
    'navigate':{'navigation':'n.','navigator':'n.'},
    'necessary':{'necessarily':'adv.','necessity':'n.'},
    'neglect':{'negligence':'n.','negligent':'adj.'},
    'negotiate':{'negotiation':'n.'},
    'normal':{'normally':'adv.','normalize':'v.'},
    'nourish':{'nourishment':'n.','nourishing':'adj.'},
    'object':{'objection':'n.','objective':'adj.'},
    'observe':{'observation':'n.','observer':'n.'},
    'obtain':{'obtainable':'adj.','obtained':'adj.'},
    'occupy':{'occupation':'n.','occupied':'adj.'},
    'operate':{'operation':'n.','operational':'adj.'},
    'oppose':{'opposition':'n.','opposed':'adj.'},
    'organize':{'organization':'n.','organized':'adj.'},
    'origin':{'original':'adj.','originally':'adv.'},
    'participate':{'participation':'n.','participant':'n.'},
    'patient':{'patience':'n.','patiently':'adv.'},
    'perceive':{'perception':'n.','perceptive':'adj.'},
    'perform':{'performance':'n.','performer':'n.'},
    'permit':{'permission':'n.','permissible':'adj.'},
    'persist':{'persistence':'n.','persistent':'adj.'},
    'persuade':{'persuasion':'n.','persuasive':'adj.'},
    'phenomenon':{'phenomenal':'adj.'},
    'pollute':{'pollution':'n.','pollutant':'n.'},
    'popular':{'popularity':'n.','popularize':'v.'},
    'possess':{'possession':'n.','possessive':'adj.'},
    'possible':{'possibility':'n.','possibly':'adv.'},
    'predict':{'prediction':'n.','predictable':'adj.'},
    'prefer':{'preference':'n.','preferable':'adj.'},
    'prepare':{'preparation':'n.','prepared':'adj.'},
    'prescribe':{'prescription':'n.'},
    'preserve':{'preservation':'n.','preservative':'adj.'},
    'prevent':{'prevention':'n.','preventable':'adj.'},
    'proceed':{'procedure':'n.','proceeding':'n.'},
    'produce':{'production':'n.','productive':'adj.'},
    'profession':{'professional':'adj.'},
    'profit':{'profitable':'adj.','profitability':'n.'},
    'progress':{'progressive':'adj.'},
    'prohibit':{'prohibition':'n.','prohibited':'adj.'},
    'promote':{'promotion':'n.','promotional':'adj.'},
    'propose':{'proposal':'n.','proposed':'adj.'},
    'protect':{'protection':'n.','protective':'adj.'},
    'prove':{'proof':'n.','proven':'adj.'},
    'provide':{'provision':'n.','provided':'conj.'},
    'provoke':{'provocation':'n.','provocative':'adj.'},
    'public':{'publicity':'n.','publicize':'v.'},
    'publish':{'publication':'n.','published':'adj.'},
    'punish':{'punishment':'n.'},
    'pursue':{'pursuit':'n.'},
    'qualify':{'qualification':'n.','qualified':'adj.'},
    'react':{'reaction':'n.','reactive':'adj.'},
    'real':{'reality':'n.','realistic':'adj.'},
    'realize':{'realization':'n.'},
    'receive':{'reception':'n.','recipient':'n.'},
    'recognize':{'recognition':'n.','recognizable':'adj.'},
    'recommend':{'recommendation':'n.'},
    'recover':{'recovery':'n.'},
    'reduce':{'reduction':'n.','reduced':'adj.'},
    'refer':{'reference':'n.'},
    'reflect':{'reflection':'n.','reflective':'adj.'},
    'regard':{'regardless':'adv.','regarding':'prep.'},
    'register':{'registration':'n.'},
    'regulate':{'regulation':'n.','regulatory':'adj.'},
    'reinforce':{'reinforcement':'n.'},
    'reject':{'rejection':'n.'},
    'relate':{'relation':'n.','relationship':'n.'},
    'reliable':{'reliability':'n.','reliably':'adv.','reliance':'n.'},
    'relieve':{'relief':'n.','relieved':'adj.'},
    'remain':{'remainder':'n.','remaining':'adj.'},
    'remove':{'removal':'n.','removed':'adj.'},
    'renew':{'renewal':'n.','renewable':'adj.'},
    'represent':{'representation':'n.','representative':'n.'},
    'require':{'requirement':'n.','required':'adj.'},
    'reserve':{'reservation':'n.','reserved':'adj.'},
    'resist':{'resistance':'n.','resistant':'adj.'},
    'resolve':{'resolution':'n.','resolved':'adj.'},
    'respond':{'response':'n.','responsive':'adj.'},
    'responsible':{'responsibility':'n.'},
    'restore':{'restoration':'n.'},
    'restrict':{'restriction':'n.','restrictive':'adj.'},
    'retain':{'retention':'n.'},
    'retire':{'retirement':'n.'},
    'reveal':{'revelation':'n.'},
    'revise':{'revision':'n.'},
    'revolution':{'revolutionary':'adj.'},
    'satisfy':{'satisfaction':'n.','satisfactory':'adj.'},
    'secure':{'security':'n.','secured':'adj.'},
    'select':{'selection':'n.','selective':'adj.'},
    'sensitive':{'sensitivity':'n.','sensible':'adj.'},
    'separate':{'separation':'n.','separately':'adv.'},
    'signify':{'significant':'adj.','significance':'n.'},
    'similar':{'similarity':'n.','similarly':'adv.'},
    'simplify':{'simplification':'n.','simplified':'adj.'},
    'solve':{'solution':'n.'},
    'special':{'specialize':'v.','specialist':'n.'},
    'specific':{'specifically':'adv.','specify':'v.'},
    'stable':{'stability':'n.','stabilize':'v.'},
    'stimulate':{'stimulation':'n.','stimulating':'adj.'},
    'strengthen':{'strength':'n.'},
    'struggle':{'struggling':'adj.'},
    'submit':{'submission':'n.'},
    'succeed':{'success':'n.','successful':'adj.'},
    'sufficient':{'sufficiently':'adv.','insufficient':'adj.'},
    'suggest':{'suggestion':'n.','suggestive':'adj.'},
    'support':{'supportive':'adj.','supporter':'n.'},
    'survive':{'survival':'n.','survivor':'n.'},
    'suspect':{'suspicion':'n.','suspicious':'adj.'},
    'sustain':{'sustainable':'adj.','sustainability':'n.'},
    'symbol':{'symbolic':'adj.','symbolize':'v.'},
    'sympathy':{'sympathetic':'adj.'},
    'tend':{'tendency':'n.'},
    'terrify':{'terror':'n.','terrifying':'adj.'},
    'tolerate':{'tolerance':'n.','tolerable':'adj.'},
    'transform':{'transformation':'n.','transformative':'adj.'},
    'translate':{'translation':'n.','translator':'n.'},
    'transmit':{'transmission':'n.'},
    'treat':{'treatment':'n.','treaty':'n.'},
    'undergo':{'undergoing':'adj.'},
    'understand':{'understanding':'n.','understandable':'adj.'},
    'urge':{'urgent':'adj.','urgency':'n.'},
    'utilize':{'utilization':'n.'},
    'valid':{'validity':'n.','validate':'v.'},
    'value':{'valuable':'adj.','valuation':'n.'},
    'vary':{'variety':'n.','variation':'n.','various':'adj.'},
    'verify':{'verification':'n.'},
    'violate':{'violation':'n.','violator':'n.'},
    'volunteer':{'voluntary':'adj.','voluntarily':'adv.'},
    'warn':{'warning':'n.'},
    'withdraw':{'withdrawal':'n.'},
    'worth':{'worthy':'adj.','worthwhile':'adj.'},
    'yield':{'yielding':'adj.','unyielding':'adj.'},
}

# --- phases map (word -> [phrase1, phrase2, ...]) ---
PHR = {
    'abandon':['abandon ship','abandon hope','abandon oneself'],
    'absorb':['absorb information','absorb the cost','be absorbed in'],
    'accelerate':['accelerate growth','accelerate the pace'],
    'accept':['accept responsibility','accept an invitation'],
    'access':['access to','have access to'],
    'accommodate':['accommodate to','accommodate guests'],
    'accompany':['accompany by','be accompanied by'],
    'accomplish':['accomplish a goal','accomplish the mission'],
    'accumulate':['accumulate wealth','accumulate experience'],
    'achieve':['achieve success','achieve the goal'],
    'acknowledge':['acknowledge receipt','acknowledge the fact'],
    'acquire':['acquire knowledge','acquire a taste for'],
    'adapt':['adapt to change','adapt oneself to'],
    'addict':['be addicted to'],
    'address':['address the issue','address a letter'],
    'adjust':['adjust to','adjust the settings'],
    'admire':['admire for','admire the view'],
    'adopt':['adopt a policy','adopt a child'],
    'advance':['advance in','make advances'],
    'affect':['affect the outcome','deeply affected'],
    'agree':['agree with','agree on','agree to'],
    'allocate':['allocate resources','allocate funds'],
    'alter':['alter the course','alter the plan'],
    'analyze':['analyze data','analyze the situation'],
    'announce':['announce the results','announce that'],
    'anticipate':['anticipate needs','anticipate problems'],
    'apologize':['apologize for','apologize to'],
    'apply':['apply for','apply to','apply pressure'],
    'appreciate':['appreciate art','appreciate the effort'],
    'approach':['approach the problem','take an approach'],
    'approve':['approve of','approve the plan'],
    'argue':['argue about','argue that','argue against'],
    'arrange':['arrange a meeting','arrange for'],
    'assess':['assess the damage','assess the risk'],
    'assign':['assign blame','assign a task','assign responsibility'],
    'assist':['assist with','assist in'],
    'associate':['associate with','be associated with'],
    'assume':['assume responsibility','assume the worst'],
    'assure':['assure of','rest assured'],
    'attach':['attach importance to','attach a file'],
    'attempt':['attempt to do','make an attempt'],
    'attend':['attend a meeting','attend to'],
    'attract':['attract attention','attract investment'],
    'avoid':['avoid doing','avoid the issue'],
    'balance':['balance work and life','strike a balance'],
    'bear':['bear in mind','bear the burden','bear fruit'],
    'believe':['believe in','believe that'],
    'benefit':['benefit from','mutual benefit'],
    'boost':['boost the economy','boost morale'],
    'bore':['bore with','be bored with'],
    'bound':['bound to','be bound by','out of bounds'],
    'break':['break down','break through','break up'],
    'bring':['bring about','bring up','bring forward'],
    'calculate':['calculate on','calculate the cost'],
    'capture':['capture attention','capture the moment'],
    'carry':['carry out','carry on','carry weight'],
    'cast':['cast doubt on','cast a shadow','cast a vote'],
    'catch':['catch up with','catch on','catch a glimpse'],
    'cause':['cause and effect','cause trouble'],
    'challenge':['challenge the status quo','face a challenge'],
    'change':['change mind','change over time'],
    'charge':['take charge of','free of charge','charge with'],
    'check':['check in','check out','check on'],
    'claim':['claim responsibility','make a claim'],
    'classify':['classify into','classify as'],
    'collapse':['collapse under pressure','economic collapse'],
    'combine':['combine with','combine efforts'],
    'come':['come across','come up with','come to terms'],
    'commit':['commit to','commit a crime','commit oneself'],
    'communicate':['communicate with','communicate effectively'],
    'compare':['compare with','compare to','beyond compare'],
    'compete':['compete with','compete for'],
    'complain':['complain about','complain of'],
    'complete':['complete the task','complete works'],
    'concentrate':['concentrate on','concentrate efforts'],
    'concern':['concern about','show concern for'],
    'conclude':['conclude with','conclude that'],
    'conduct':['conduct research','conduct an experiment'],
    'confirm':['confirm the reservation','confirm that'],
    'conflict':['conflict with','in conflict','conflict of interest'],
    'confront':['confront the issue','be confronted with'],
    'connect':['connect with','connect to','stay connected'],
    'consider':['consider doing','consider the possibility'],
    'consist':['consist of','consist in'],
    'construct':['construct a theory','construct a building'],
    'consume':['consume resources','consume time'],
    'contain':['contain the spread','contain oneself'],
    'contribute':['contribute to','make a contribution'],
    'control':['take control of','under control','out of control'],
    'convert':['convert to','convert into'],
    'convey':['convey a message','convey the meaning'],
    'convince':['convince of','convince to do'],
    'cope':['cope with','cope with stress'],
    'correspond':['correspond to','correspond with'],
    'count':['count on','count down','count for'],
    'cover':['cover up','cover the cost','cover a topic'],
    'create':['create opportunities','create problems'],
    'criticize':['criticize for','criticize harshly'],
    'cut':['cut down on','cut off','cut through'],
    'deal':['deal with','a great deal of','close the deal'],
    'debate':['debate on','a heated debate'],
    'decide':['decide on','decide whether to'],
    'declare':['declare war','declare independence'],
    'decline':['decline an invitation','in decline'],
    'define':['define as','define the boundaries'],
    'deliver':['deliver a speech','deliver goods','deliver results'],
    'demand':['demand for','in demand','meet the demand'],
    'demonstrate':['demonstrate the ability','demonstrate against'],
    'deny':['deny doing','deny the charge'],
    'depend':['depend on','it depends'],
    'describe':['describe as','describe in detail'],
    'design':['design for','by design','design a system'],
    'determine':['determine to do','determine the cause'],
    'develop':['develop skills','develop a plan'],
    'devote':['devote to','devote oneself to'],
    'differ':['differ from','differ in','beg to differ'],
    'direct':['direct attention to','take direct action'],
    'discover':['discover the truth','discover new lands'],
    'discuss':['discuss with','discuss the matter'],
    'dismiss':['dismiss the idea','dismiss from'],
    'display':['on display','display the results'],
    'dispose':['dispose of','dispose waste'],
    'distinguish':['distinguish between','distinguish from'],
    'distribute':['distribute to','distribute leaflets'],
    'divide':['divide into','divide by','digital divide'],
    'dominate':['dominate the market','dominant position'],
    'doubt':['doubt about','without doubt','cast doubt on'],
    'draw':['draw attention to','draw a conclusion','draw on'],
    'drop':['drop out of','drop by','drop the idea'],
    'earn':['earn a living','earn respect','earn interest'],
    'effect':['take effect','have an effect on','in effect'],
    'eliminate':['eliminate poverty','eliminate risks'],
    'emerge':['emerge from','emerging market'],
    'emphasize':['emphasize the importance','put emphasis on'],
    'employ':['employ a method','employ workers'],
    'enable':['enable to do','enable access'],
    'encounter':['encounter difficulties','a chance encounter'],
    'encourage':['encourage someone','encourage innovation'],
    'engage':['engage in','be engaged'],
    'enhance':['enhance performance','enhance security'],
    'ensure':['ensure that','ensure safety'],
    'establish':['establish a company','well-established'],
    'evaluate':['evaluate performance','conduct an evaluation'],
    'evolve':['evolve over time','evolution of'],
    'examine':['examine the evidence','examine carefully'],
    'exceed':['exceed expectations','exceed the limit'],
    'exchange':['exchange ideas','in exchange for','exchange rate'],
    'exclude':['exclude from','exclusive rights'],
    'exercise':['exercise regularly','exercise right'],
    'exist':['exist in','cease to exist'],
    'expand':['expand market','expand rapidly'],
    'expect':['expect to','meet expectations'],
    'experience':['gain experience','first-hand experience'],
    'explain':['explain to','explain the reason'],
    'exploit':['exploit resources','exploit the weakness'],
    'explore':['explore options','explore new territory'],
    'expose':['expose to','expose the truth'],
    'express':['express oneself','express concern'],
    'extend':['extend to','extend deadline'],
    'face':['face a challenge','face to face','in the face of'],
    'facilitate':['facilitate communication','facilitate the process'],
    'fail':['fail to do','fail the test','without fail'],
    'fall':['fall behind','fall into','fall apart'],
    'favor':['in favor of','do a favor'],
    'figure':['figure out','public figure','figure of speech'],
    'focus':['focus on','bring into focus','out of focus'],
    'follow':['follow up','follow the rules','as follows'],
    'force':['force to do','in force','come into force'],
    'fulfill':['fulfill a dream','fulfill the requirements'],
    'gain':['gain access to','gain experience','gain weight'],
    'generate':['generate revenue','generate interest'],
    'get':['get along with','get over','get through'],
    'give':['give up','give rise to','give away'],
    'go':['go through','go on','go after'],
    'grant':['take for granted','grant a request'],
    'guard':['guard against','on guard','off guard'],
    'handle':['handle the situation','handle with care'],
    'hold':['hold on','hold a meeting','hold true'],
    'identify':['identify with','identify the problem'],
    'ignore':['ignore the fact','ignore completely'],
    'impact':['impact on','have an impact on'],
    'implement':['implement a plan','implement changes'],
    'imply':['imply that','as the name implies'],
    'impose':['impose on','impose restrictions'],
    'impress':['impress on','be impressed by'],
    'improve':['improve on','improve the quality'],
    'increase':['increase by','increase in','on the increase'],
    'indicate':['indicate that','indicate the direction'],
    'influence':['influence on','under the influence'],
    'inform':['inform of','inform about','keep informed'],
    'insist':['insist on','insist that'],
    'integrate':['integrate into','integrate with'],
    'intend':['intend to do','intend for','as intended'],
    'interact':['interact with','interact socially'],
    'interpret':['interpret as','interpret the data'],
    'introduce':['introduce to','introduce oneself'],
    'invest':['invest in','invest time and effort'],
    'investigate':['investigate the case','investigate further'],
    'involve':['involve in','get involved with','involve doing'],
    'keep':['keep in mind','keep up with','keep on doing'],
    'lack':['lack of','lack the ability','for lack of'],
    'launch':['launch a campaign','launch into'],
    'lead':['lead to','lead by example','take the lead'],
    'learn':['learn from','learn about','learn the lesson'],
    'limit':['limit to','time limit','off limits'],
    'look':['look for','look forward to','look into'],
    'lose':['lose weight','lose control','lose track'],
    'maintain':['maintain order','maintain relationships'],
    'make':['make sure','make a difference','make sense'],
    'manage':['manage to do','manage a business'],
    'manufacture':['manufacture goods','manufacturing industry'],
    'measure':['measure up to','take measures'],
    'merge':['merge with','merge into','merge companies'],
    'monitor':['monitor progress','monitor closely'],
    'motivate':['motivate to do','keep motivated'],
    'negotiate':['negotiate with','negotiate a deal'],
    'obtain':['obtain from','obtain permission'],
    'offer':['offer to do','make an offer','on offer'],
    'operate':['operate on','operate a machine'],
    'oppose':['oppose to','as opposed to','oppose the plan'],
    'organize':['organize an event','organize data'],
    'overcome':['overcome difficulties','overcome fear'],
    'participate':['participate in','participate actively'],
    'pass':['pass away','pass on','pass the test'],
    'pay':['pay attention to','pay for','pay off'],
    'perform':['perform well','perform a task'],
    'persist':['persist in','if symptoms persist'],
    'persuade':['persuade to do','persuade of'],
    'point':['point out','point of view','to the point'],
    'pose':['pose a threat','pose a question'],
    'predict':['predict the future','predict accurately'],
    'prefer':['prefer to','prefer over','would prefer'],
    'prepare':['prepare for','prepare to do','be prepared'],
    'present':['present a report','at present'],
    'preserve':['preserve food','preserve peace'],
    'prevent':['prevent from','prevent the spread'],
    'proceed':['proceed with','proceed to do'],
    'produce':['produce results','produce goods'],
    'promote':['promote to','promote health'],
    'propose':['propose a plan','propose to do'],
    'protect':['protect from','protect against'],
    'prove':['prove to be','prove a point'],
    'provide':['provide with','provide for'],
    'pursue':['pursue a career','pursue happiness'],
    'put':['put forward','put up with','put into practice'],
    'qualify':['qualify for','qualify as'],
    'raise':['raise awareness','raise funds','raise a question'],
    'range':['range from','a wide range of'],
    'reach':['reach a conclusion','reach out to','within reach'],
    'react':['react to','react against'],
    'realize':['realize the importance','realize a dream'],
    'receive':['receive attention','receive treatment'],
    'recognize':['recognize as','recognize the importance'],
    'recover':['recover from','recover consciousness'],
    'reduce':['reduce to','reduce the risk','reduce costs'],
    'refer':['refer to','refer to as'],
    'reflect':['reflect on','reflect the reality'],
    'refuse':['refuse to do','refuse point-blank'],
    'regard':['regard as','with regard to','in this regard'],
    'relate':['relate to','be related to'],
    'release':['release from','press release'],
    'relieve':['relieve stress','relieve pain'],
    'rely':['rely on','rely heavily on'],
    'remain':['remain silent','remain loyal'],
    'remove':['remove from','remove obstacles'],
    'replace':['replace with','replace by'],
    'represent':['represent interests of'],
    'require':['require that','require attention'],
    'resolve':['resolve the issue','resolve to do'],
    'respond':['respond to','respond quickly'],
    'restore':['restore order','restore confidence'],
    'restrict':['restrict to','restrict access'],
    'result':['result in','result from','as a result'],
    'retain':['retain control','retain information'],
    'reveal':['reveal the truth','reveal oneself'],
    'reverse':['reverse the trend','in reverse'],
    'rise':['give rise to','rise to the challenge','on the rise'],
    'risk':['at risk','take a risk','risk doing'],
    'rule':['rule out','as a rule','rule over'],
    'run':['run into','run out of','in the long run'],
    'seek':['seek out','seek to do','seek help'],
    'sense':['make sense','a sense of','common sense'],
    'separate':['separate from','separate into'],
    'serve':['serve as','serve the purpose'],
    'set':['set up','set out to do','set an example'],
    'settle':['settle down','settle for','settle a dispute'],
    'share':['share with','fair share','market share'],
    'shed':['shed light on','shed tears'],
    'shift':['shift from','shift the blame'],
    'show':['show off','show up','show concern'],
    'sign':['sign up for','sign a contract'],
    'solve':['solve the problem','solve a mystery'],
    'sort':['sort out','sort of','of all sorts'],
    'speak':['speak out','speak of','so to speak'],
    'spend':['spend on','spend time doing','spend money'],
    'spread':['spread out','spread the word'],
    'stand':['stand out','stand for','stand by'],
    'stay':['stay up','stay away from','stay in touch'],
    'stimulate':['stimulate growth','stimulate the economy'],
    'strengthen':['strengthen ties','strengthen the position'],
    'stress':['stress the importance','under stress'],
    'struggle':['struggle with','struggle for','struggle to do'],
    'submit':['submit to','submit a report'],
    'succeed':['succeed in','succeed to the throne'],
    'suffer':['suffer from','suffer losses'],
    'suggest':['suggest that','suggest doing'],
    'support':['support for','in support of'],
    'suppose':['be supposed to','suppose that'],
    'survive':['survive on','survive the accident'],
    'suspect':['suspect of','suspect that'],
    'sustain':['sustain damage','sustain growth'],
    'tackle':['tackle the problem','tackle the issue'],
    'take':['take on','take over','take into account'],
    'talk':['talk about','talk over','small talk'],
    'tell':['tell apart','tell the truth'],
    'tend':['tend to do','tend to be','tend towards'],
    'think':['think about','think over','think highly of'],
    'trace':['trace back to','without a trace'],
    'track':['keep track of','on the right track','track down'],
    'transfer':['transfer to','transfer funds'],
    'transform':['transform into','transform the industry'],
    'treat':['treat as','treat with respect'],
    'trigger':['trigger a reaction','trigger the alarm'],
    'trust':['trust in','trust with','build trust'],
    'try':['try out','try on','try best'],
    'turn':['turn out','turn down','in turn'],
    'undergo':['undergo changes','undergo surgery'],
    'undermine':['undermine authority','undermine confidence'],
    'undertake':['undertake a task','undertake to do'],
    'urge':['urge to do','urge caution'],
    'vary':['vary from','vary widely','vary in'],
    'verify':['verify the information','verify the identity'],
    'view':['view as','point of view','in view of'],
    'violate':['violate the law','violate privacy'],
    'vote':['vote for','vote against','cast a vote'],
    'warn':['warn of','warn against','warn that'],
    'weigh':['weigh the pros and cons','weigh on'],
    'win':['win over','win back','win the prize'],
    'withdraw':['withdraw from','withdraw money'],
    'work':['work out','work on','work for'],
    'yield':['yield to','yield results','high yield'],
}

# --- Build reverse index ---
REV = {}
for base, ders in DERIV.items():
    for d, p in ders.items():
        REV.setdefault(d, []).append(base)

# --- Parse all lines ---
raw = open(SRC, 'rb').read()
text = raw.decode('utf-8')
all_entries = []

for line in text.split('\n'):
    line = line.strip()
    if not line or '\t' not in line or len(line) < 5:
        continue
    parts = line.split('\t')
    if len(parts) < 2:
        continue
    w = re.match(r'^([a-z\-]+)', parts[0].strip(), re.I)
    if not w:
        continue
    word = w.group(1).strip()
    wl = word.lower()
    if len(word) < 2 or not re.search(r'[aeiou]', word, re.I):
        continue

    # Derivatives
    ders = []
    if wl in DERIV:
        for dw, dp in DERIV[wl].items():
            ders.append(f"{dw} ({dp})")
    elif wl in REV:
        for bw in REV[wl]:
            ders.append(f"{bw} (v.)")

    # Phrases
    phrs = []
    if wl in PHR:
        phrs = PHR[wl][:2]

    all_entries.append({
        "word": word,
        "derivatives": ders,
        "phrases": phrs
    })

print(f"Parsed {len(all_entries)} entries from source")
assert len(all_entries) >= 5500, f"Expected >=5500 entries, got {len(all_entries)}"

# --- Split into batches ---
os.makedirs(OUT, exist_ok=True)
TOTAL = len(all_entries)
NUM = max(50, (TOTAL + 112) // 113)
BS = (TOTAL + NUM - 1) // NUM

print(f"Splitting {TOTAL} words into {NUM} batches of ~{BS} each")

for i in range(NUM):
    s = i * BS
    e = min((i+1)*BS, TOTAL)
    if s >= TOTAL:
        break
    batch = all_entries[s:e]
    fname = f"words_batch_{i+1:02d}.json"
    fpath = os.path.join(OUT, fname)
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    if i < 5 or i % 10 == 0:
        print(f"  {fname}: {len(batch)} words")

print(f"\nDone! {NUM} files, {TOTAL} total entries")

# Verify
got = set(e['word'].lower() for e in all_entries)
want = set()
for line in text.split('\n'):
    line = line.strip()
    if not line or '\t' not in line or len(line) < 5:
        continue
    parts = line.split('\t')
    w = re.match(r'^([a-z\-]+)', parts[0].strip(), re.I)
    if w:
        ww = w.group(1).strip().lower()
        if len(ww) >= 2 and re.search(r'[aeiou]', ww, re.I):
            want.add(ww)
missed = want - got
if missed:
    print(f"WARNING: {len(missed)} words missed: {list(missed)[:20]}")
else:
    print("ALL words covered!")

with_deriv = sum(1 for e in all_entries if e['derivatives'])
with_phr = sum(1 for e in all_entries if e['phrases'])
print(f"Derivatives: {with_deriv}/{TOTAL}  Phrases: {with_phr}/{TOTAL}")